### PR TITLE
Add Doom Unity patch format

### PR DESCRIPTION
**Pull request by XaserAcheron**
Just a quick n' dirty patch format for the Unity port -- same as Ultimate Doom v1.9, without string length limits.

No worries if you'd rather approach this a different way; just figured I'd whip this up while I was in the neighborhood.

### CODE REVIEW

**Review by MTrop — CHANGES_REQUESTED** [review]
Looks good - the only thing I'd change, though, is that `Boolean` type should be the primitive type `boolean` rather than the boxed one, since that value should never be null.

**Comment by MTrop** [comment]
I have changed the base branch on my end to `decohack-doomunity` to make a merge easier to a branch that isn't in flux.

**Comment by XaserAcheron** [comment]
My bad, I forgot about this :P -- made the requested changes and fixed the merge conflicts, so it should be all good to go now.

**Review by MTrop — APPROVED** [review]
Approved. Time to merge!

**Pull request merged**
